#!/usr/bin/env ruby
# {!} info Command line interface made by Felipe Vieira for Escriba
# {!} info It reads an filename from arguments , parse the lines and print them.
require './core/borotoPrinter.rb'
require './core/borotoParser.rb'
$borotoVersion = "3.0.0"
# {!} function functions displayHelp, a simple function to display an usage mesage
def displayHelp
  puts ""
  puts "Usage: ./boroto <name-of-document-to-parse>"
  puts "Boroto #{$borotoVersion}: PHP Class with ActiveRecord and primitive ORM generator from SQL"
  puts "Made by Felipe Vieira"
  exit
end

if ARGV.length == 0
  puts "too few arguments"
  displayHelp
end

if ARGV.length > 1
  puts "too much arguments"
  displayHelp
end
puts "Boroto, Version ActiveRecord #{$borotoVersion}. Reading file #{ARGV[0]}"
puts "Initializing..."
parser = BorotoParser.new

counterlines = 0
parsedlines = 0

begin
  input = File.open(ARGV[0],"r")
  puts "Parsing..."
  while (buffer = input.gets)

    if parser.parse buffer
      parsedlines = parsedlines + 1
    end
    counterlines = counterlines + 1

  end
  input.close
rescue Exception => err
  puts "Error reading file"
  puts err
  displayHelp
  puts "exit"
end

puts "#{counterlines} lines processed"
puts "#{parsedlines} lines parsed"
puts "Parsed"
if parser.bcArray.empty?
  puts "no classes have been found"
  exit
end
parser.bcArray.each do |boroto|
  puts "#{boroto.name} \tclass found"
end
puts "Writing to disk..."
parser.bcArray.each do |borotoclass|
  newPrinter = BorotoPrinter.new borotoclass
  newPrinter.printClass
  newPrinter.save
end
puts "Completed"
